<div id="hot_list">
<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td height="51" background="image/index2_07.gif"></td>
</tr>
<tr>
	<td id="list">
	<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0" background="image/index1_13.gif">
	<tr>
		<td><li><a href="#">1 空中危机</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">2 僵尸新娘</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">3 宛如天堂</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">4 冰上迪斯科</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">5 驱魔</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">6 战争之王</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">7 四十岁的老处男</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">8 不朽的园丁</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">9 非常人贩</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">10 狼来了</a></li></td>
	</tr>
	</table>
	</td>
</tr>
<tr>
	<td><img src="image/index2_08.gif" width="200" height="15"></td>
</tr>
</table>
</div>