<div id="login">
<table width="100%" border="0" cellpadding="0" cellspacing="0" style="color:#ffffff">
<form name="form1" method="post" action="">
<tr>
	<td height="34" colspan="2"><span style="margin-left:18px;color:#fddd04;font-family:WST_ENGl">WWW.PANSKY.NET</span></td>
</tr>
<tr>
	<td height="20" colspan="2"><span style="margin-left:54px">用户登录</span></td>
</tr>
<tr>
	<td width="65" height="16"></td><td></td>
</tr>
<tr>
	<td height="24" align="right">帐号：</td>
	<td><input type="text" name="account" size="16" class="input_text"></td>
</tr>
<tr>
	<td height="24" align="right">密码：</td>
	<td><input type="password" name="password" size="16" class="input_text"></td>
</tr>
<tr>
	<td height="24" align="right">验证码：</td>
	<td><input type="text" name="validate" size="6" class="input_text"> <img src="image/src/vali.jpg" align="absmiddle"></td>
</tr>
<tr>
	<td height="24" colspan="2"><span style="margin-left:16px">记住帐号：</span><input type="checkbox" name="keepme" value="1">&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" name="Submit1" value=" 登 录 " style="background-image:url('image/index1_04.gif')"></td>
</tr>
<tr>
	<td height="24" colspan="2" align="center"><input type="button" name="button1" value="注册">&nbsp;&nbsp;<input type="button" name="button2" value="忘记密码"></td>
</tr>
</form>
</table>
</div>