<div id="news">
<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="8" height="8" background="image/index2_04.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td width="8" background="image/index2_05.gif"></td>
</tr>
<tr>
	<td bgcolor="#ffffff"></td>
	<td height="48" valign="top" bgcolor="#ffffff" background="image/index2_13.gif" style="background-position:top;background-repeat:no-repeat"></td>
	<td bgcolor="#ffffff"></td>
</tr>
<tr>
	<td bgcolor="#ffffff"></td>
	<td id="news">
	<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffffff">
	<tr>
		<td><li><a href="#">公司与网通公司建立战</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">建设面向PC用户和家易</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">以用户为中心，提供正</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">IPTV电视节目以及其他</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">成为一个提供高质量服</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">高起点的节目内容提供</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">让用户和网通认可的优</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">目前网通的网站上已有</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">我公司的网站首先要</a></li></td>
	</tr>
	<tr>
		<td><li><a href="#">我公司的网站首先要</a></li></td>
	</tr>
	</table>
	</td>
	<td bgcolor="#ffffff"></td>
</tr>
<tr>
	<td height="8" background="image/index2_10.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td background="image/index2_11.gif"></td>
</tr>
</table>
</div>