<div id="ad">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="8" height="8" background="image/index2_04.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td width="8" background="image/index2_05.gif"></td>
</tr>
<tr>
	<td bgcolor="#ffffff"></td>
	<td bgcolor="#ffffff">
	<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td><a href="javascript:goUrl()"><img src="javascript:nextAd()" name="imgInit" border=0 style="FILTER: revealTrans(duration=1,transition=23);" width="505" height="192"></a></td>
	</tr>
	</table>
	</td>
	<td bgcolor="#ffffff"></td>
</tr>
<tr>
	<td height="8" background="image/index2_10.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td background="image/index2_11.gif"></td>
</tr>
</table>
</div>