<div id="footer">
<table width="975" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffe2c6" style="margin-bottom:20px">
<tr>
	<td width="8" height="8" background="image/index2_16.gif"></td>
	<td></td>
	<td width="8" background="image/index2_17.gif"></td>
</tr>
<tr>
	<td></td>
	<td>
	<table id="footer" width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td height="26" align="center" background="image/index1_19.gif"><a href="#">联系我们</a> <span style="color:#ffffff">|</span> <a href="#">关于我们</a></td>
	</tr>
	<tr>
		<td height="50" align="center">长天影视版权所有 &copy;2005-2006</td>
	</tr>
	</table>
	</td>
	<td></td>
</tr>
<tr>
	<td height="8" background="image/index2_18.gif"></td>
	<td></td>
	<td background="image/index2_19.gif"></td>
</tr>
</table>
</div>