<div id="main">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="8" height="8" background="image/index2_04.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td width="8" background="image/index2_05.gif"></td>
</tr>
<tr>
	<td bgcolor="#ffffff"></td>
	<td bgcolor="#ffffff">
	<table id="fullnavi" width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td width="48" height="42"><img src="image/main1_01.gif"></td>
		<td background="image/main1_02.gif"><span class="fullnavi">您的位置:<a href="#">电影</a>&gt;&gt;<a href="#">动作片</a>&gt;&gt;影片详细信息</span></td>
		<td width="9"><img src="image/main1_03.gif"></td>
	</tr>
	</table>
	<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffffff" style="margin-top:40px">
	<tr>
		<td id="movie_info">
		<table width="100%" border="0" cellpadding="0" cellspacing="10" bgcolor="#ffffff">
		<tr>
			<td><img src="image/src/haibao.jpg" class="big">
			<p>
			电影名称：《极限刺侠》<br>
			主要演员：金城武 铃木杏<br>
			电影类型：动作片<br>
			文件格式：RMVB<br>
			推荐指数：★★★★★<br>
			观看次数：999次<br>
			下载次数：99次<br>
			内容简介：太龙（金城武饰）是一个“Returner”，责任是替聘用者潜入黑市的深处，盗取大笔大笔的无迹可寻的巨款，以极高效率将款项安全交到聘用者手上。太龙本为一个孤儿，他的童年好友喜宽被一个神秘人杀死，太龙下定决心要找出凶手报仇。在横滨的海岸，太龙正要潜入另一个地下世界，遇上当年杀死他好友的凶手。太龙按捺不住激动的情绪展开一场死斗时，错手枪伤了一名来自未来的无辜少女美里（铃木杏饰）。美里大难不死，还聘请太龙替她完成一项特别任务，携手在两天内将世界从危难中解脱…… 
			</p></td>
		</tr>
		<tr>
			<td align="center"><a href="#"><img src="image/main2_01.gif" width="88" height="20" border="0"></a></td>
		</tr>
		<tr>
			<td height="1" background="image/index2_22.gif"></td>
		</tr>
		<tr>
			<td id="relat_movie">相关影片：<br>
			<table width="100%" border="0" cellpadding="8" cellspacing="0" bgcolor="#ffffff">
			<tr>
				<td align="center"><img src="image/src/h1.jpg" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼"><br><a href="info.htm" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
				<td align="center"><img src="image/src/h1.jpg"><br><a href="#" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
				<td align="center"><img src="image/src/h1.jpg"><br><a href="#" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
				<td align="center"><img src="image/src/h1.jpg" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼"><br><a href="#" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
				<td align="center"><img src="image/src/h1.jpg" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼"><br><a href="#" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
			</tr>
			</table>
			</td>
		</tr>
		<tr>
			<td height="1" background="image/index2_22.gif"></td>
		</tr>
		<tr>
			<td id="topic">
			<table width="80%" border="0" cellpadding="2" cellspacing="1" bgcolor="#61C838" align="center">
			<form name="form3" method="post">
			<tr>
				<td height="26" colspan="4" background="image/main2_05.gif" style="padding:0"><img src="image/main2_02.gif" width="24" height="26" align="absmiddle" style="margin-left:10px;"><span style="margin-left:5px;color:#ffffff;font-size:13px;font-weight:bold">相关评论：</span><span id="topic2">共<span style="color:#00ff00;font-weight:bold">2</span>条评论 <a href="#" target="_blank">查看完整内容</a></span></td>
			</tr>
			<tr bgcolor="#ffffff">
				<td height="26"></td>
				<td align="center" nowrap>评论人</td>
				<td align="center">评论内容</td>
				<td align="center">发表时间</td>
			</tr>
			<tr bgcolor="#ffffff">
				<td nowrap><span style="color:#ff0000">2</span> 楼 <a href="#">[回复]</a></td>
				<td nowrap align="center">abc</td>
				<td>真的很不错哦</td>
				<td nowrap>01-18 12:12</td>
			</tr>
			<tr bgcolor="#ffffff">
				<td><span style="color:#ff0000">1</span> 楼 <a href="#">[回复]</a></td>
				<td align="center">defghijkl</td>
				<td>还是没什么说的,唉，看起来真不错，看起来真不错，看起来真不错，看起来真不错，看起来真不错，</td>
				<td>01-18 12:10</td>
			</tr>
			<tr bgcolor="#ffffff">
				<td colspan="4">
				<br>
				<span style="color:#0000A6;font-size:13px;font-weight:bold">发表评论：</span><br>
				<hr size="0.5" width="165" align="left" style="color:#0000A6">
				联系方式：<input type="text" name="contact" size="15"><br>
				（此信息有助于我们与您联系,<input type="radio" name="open" value="0" checked>不对外公开 <input type="radio" name="open" value="1">对外公开）<br>
				笔 名 <span style="color:#ff0000">*</span> ：<input type="text" name="nick" size="15"><br>
				评论内容 <span style="color:#ff0000">*</span> ：（最多1000字。当前字数：<span id="wordCount" style="color:#ff0000">0</span>）
				<textarea name="content" rows="5" cols="60" onKeyUp="wordCount()" onKeyDown="wordCount()"></textarea><br>
				表 情：<input type="radio" name="face" value="0" checked>无 
				<input type="radio" name="face" value="1"><img src="image/face/001.gif" width="20" height="20">
				<input type="radio" name="face" value="2"><img src="image/face/031.gif" width="20" height="20">
				<input type="radio" name="face" value="3"><img src="image/face/040.gif" width="20" height="20">
				<input type="radio" name="face" value="4"><img src="image/face/046.gif" width="20" height="20">
				<input type="radio" name="face" value="5"><img src="image/face/064.gif" width="20" height="20">
				<input type="radio" name="face" value="6"><img src="image/face/067.gif" width="20" height="20">
				<input type="radio" name="face" value="7"><img src="image/face/070.gif" width="20" height="20"><br>
				<input type="submit" name="submit4" value="发表我的评论">
				</td>
			</tr>
			</form>
			</table>
			</td>
		</tr>
		</table>
		</td>
	</tr>
	</table>
	</td>
	<td bgcolor="#ffffff"></td>
</tr>
<tr>
	<td height="8" background="image/index2_10.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td background="image/index2_11.gif"></td>
</tr>
</table>
</div>