<div id="main">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="8" height="8" background="image/index2_04.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td width="8" background="image/index2_05.gif"></td>
</tr>
<tr>
	<td bgcolor="#ffffff"></td>
	<td bgcolor="#ffffff">
	<!-- 最新上映 -->
	<img src="image/index1_08.gif" width="41" height="28" style="margin-top:10px"><img src="image/index1_09.gif" width="82" height="28">
	<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffffff">
	<tr>
		<td id="main_list">
		<table width="100%" border="0" cellpadding="0" cellspacing="10" bgcolor="#ffffff" style="">
		<tr>
			<td><img src="image/src/h1.jpg" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼"><br><a href="info.htm" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼"><br><a href="#" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼"><br><a href="#" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
		</tr>
		</table>
		</td>
	</tr>
	</table>
	<br>
	<img src="image/src/ad.jpg" width="748" height="77">
	<br>
	<!-- 热门影视 -->
	<img src="image/index1_08.gif" width="41" height="28" style="margin-top:10px"><img src="image/index1_14.gif" width="82" height="28">
	<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffffff">
	<tr>
		<td id="main_list">
		<table width="100%" border="0" cellpadding="0" cellspacing="10" bgcolor="#ffffff">
		<tr>
			<td><img src="image/src/h1.jpg" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼"><br><a href="#" title="《杀手无罪》&#10&#10&#10类型：电影&#10产地：美国&#10片长：单本剧&#10主演：&#13&#13&#13妮芙·坎贝尔&#13唐纳德·萨瑟兰&#13&#09威廉·梅西&#13&#09约翰·瑞特尔&#13&#09特蕾茜·乌尔曼">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#">天荒地未老</a></td>
		</tr>
		</table>
		</td>
	</tr>
	</table>
	<br>
	<img src="image/src/ad.jpg" width="748" height="77">
	<br>
	<!-- 精品影视 -->
	<img src="image/index1_08.gif" width="41" height="28" style="margin-top:10px"><img src="image/index1_16.gif" width="82" height="28">
	<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffffff">
	<tr>
		<td id="main_list">
		<table width="100%" border="0" cellpadding="0" cellspacing="10" bgcolor="#ffffff">
		<tr>
			<td><img src="image/src/h1.jpg"><br><a href="#">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#">天荒地未老</a></td>
			<td><img src="image/src/h1.jpg"><br><a href="#">天荒地未老</a></td>
		</tr>
		</table>
		</td>
	</tr>
	</table>
	</td>
	<td bgcolor="#ffffff"></td>
</tr>
<tr>
	<td height="8" background="image/index2_10.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td background="image/index2_11.gif"></td>
</tr>
</table>
</div>