<div id="top_navi">
	<div id="top_navi1"><a href="#">帮助中心</a></div>
	<div id="top_navi2"><a href="#" onclick="window.external.addFavorite('http://','长天影视')">加入收藏</a></div>
</div>

<div id="menu">
	<div id="menu1"><a href="index.php">首页</a></div>
	<div id="menu2"><a href="movie/#">电影</a></div>
	<div id="menu3"><a href="webtv/">电视</a></div>
	<div id="menu4"><a href="comic/">动漫</a></div>
	<div id="menu5"><a href="news/">新闻</a></div>
	<div id="menu6"><a href="show/">综艺</a></div>
	<div id="menu7"><a href="record/">纪实</a></div>
	<div id="menu8"><a href="mtv/">MTV</a></div>
	<div id="menu9"><a href="baike/">百科</a></div>
	<div id="menu10"><a href="subject/">专题</a></div>
</div>

<div id="submenu"><a href="type.php">科幻</a><a href="#">喜剧</a><a href="#">动画</a><a href="#">故事</a><a href="#">战争</a><a href="#">爱情</a><a href="#">恐怖</a><a href="#">惊险</a><a href="#">警匪</a><a href="#">成人</a></div>