<div id="type_list">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td height="53" background="image/index2_03.gif"></td>
</tr>
<tr>
	<td id="type_list">
	<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0" background="image/index1_07.gif">
	<tr>
		<td><b><a href="#">电影</a></b><br>
		<a href="#">科幻</a>|<a href="#">喜剧</a>|<a href="#">动画</a>|<a href="#">故事</a>|<a href="#">战争</a>|<a href="#">爱情</a>|<a href="#">恐怖</a>|<a href="#">惊险</a>|<a href="#">警匪</a>|<a href="#">成人</a></td>
	</tr>
	<tr>
		<td><b><a href="#">电视</a></b><br>
		<a href="#">欧美</a>|<a href="#">日韩</a>|<a href="#">港台</a>|<a href="#">大陆</a></td>
	</tr>
	<tr>
		<td><b><a href="#">新闻</a></b><br>
		<a href="#">今日焦点</a>|<a href="#">经济发展</a>|<a href="#">社会纵横</a>|<a href="#">时事政治</a></td>
	</tr>
	<tr>
		<td><b><a href="#">MTV</a></b><br>
		<a href="#">欧美</a>|<a href="#">日韩</a>|<a href="#">港台</a>|<a href="#">大陆</a>|<a href="#">乐队组合</a></td>
	</tr>
	<tr>
		<td><b><a href="#">百科</a></b><br>
		<a href="#">养生之道</a>|<a href="#">时尚前沿</a>|<a href="#">学习天地</a></td>
	</tr>
	</table>
	</td>
</tr>
<tr>
	<td height="15" background="image/index2_06.gif"></td>
</tr>
</table>
</div>