<!-- 正文 -->
<div id="main">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="8" height="8" background="image/index2_04.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td width="8" background="image/index2_05.gif"></td>
</tr>
<tr>
	<td bgcolor="#ffffff"></td>
	<td bgcolor="#ffffff">
	<table id="fullnavi" width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td width="48" height="42" background="image/main1_01.gif"></td>
		<td background="image/main1_02.gif"><span>您的位置:<a href="#">电影</a>&gt;&gt;动作片</span></td>
		<td width="9" background="image/main1_03.gif"></td>
	</tr>
	</table>
	<table id="type_navi" width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td align="center">共找到<span style="color:#ff0000">248</span>部电影 每页显示<span style="color:#ff0000">8</span>部 共<span style="color:#ff0000">31</span>页 当前第<span style="color:#ff0000">1</span>页 <a href="#">第一页</a> <a href="#">上一页</a> <a href="#">下一页</a> <a href="#">最后页</a> 跳转到第<select name="newpage">
		<option value="1">1</option>
		<option value="2">2</option>
		<option value="3">3</option>
		<option value="4">4</option>
		<option value="5">5</option>
		<option value="6">6</option>
		</select>页<br>
		</td>
	</tr>
	</table>
	<br>
	<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffffff">
	<tr>
		<td id="movie_list">
		<table width="100%" border="0" cellpadding="0" cellspacing="10" bgcolor="#ffffff">
		<tr>
			<td width="50%"><a href="info.php"><img src="image/src/haibao.jpg"></a>
			<p>
			片名：极限刺侠<br>演员：金城武 铃木杏<br>人气：1339<br>简介：太龙（金城武饰）是一个“Returner”，责任是替聘用者潜入黑市的深处，盗取大笔大笔的无迹可寻的巨款，以极高效率将款项安全交到聘用者手上。</p><a href="#"><img src="image/main1_04.gif" width="14" height="14" align="absmiddle" border="0" class="play">播放</a></td>
			<td width="50%"><a href="info.htm"><img src="image/src/haibao.jpg"></a>
			<p>
			片名：极限刺侠<br>演员：金城武 铃木杏<br>人气：1339<br>简介：太龙（金城武饰）是一个“Returner”，责任是替聘用者潜入黑市的深处，盗取大笔大笔的无迹可寻的巨款，以极高效率将款项安全交到聘用者手上。</p><a href="#"><img src="image/main1_04.gif" width="14" height="14" align="absmiddle" border="0" class="play">播放</a></td>
		</tr>
		<tr>
			<td height="1" colspan="2" background="image/index2_22.gif"></td>
		</tr>
		<tr>
			<td width="50%"><a href="info.htm"><img src="image/src/haibao.jpg"></a>
			<p>
			片名：极限刺侠<br>演员：金城武 铃木杏<br>人气：1339<br>简介：太龙（金城武饰）是一个“Returner”，责任是替聘用者潜入黑市的深处，盗取大笔大笔的无迹可寻的巨款，以极高效率将款项安全交到聘用者手上。
			</p>
			<a href="#"><img src="image/main1_04.gif" width="14" height="14" align="absmiddle" border="0" class="play">播放</a></td>
			<td width="50%"><a href="info.htm"><img src="image/src/haibao.jpg"></a>
			<p>
			片名：极限刺侠<br>演员：金城武 铃木杏<br>人气：1339<br>简介：太龙（金城武饰）是一个“Returner”，责任是替聘用者潜入黑市的深处，盗取大笔大笔的无迹可寻的巨款，以极高效率将款项安全交到聘用者手上。
			</p>
			<a href="#"><img src="image/main1_04.gif" width="14" height="14" align="absmiddle" border="0" class="play">播放</a></td>
		</tr>
		<tr>
			<td height="1" colspan="2" background="image/index2_22.gif"></td>
		</tr>
		<tr>
			<td width="50%"><a href="info.htm"><img src="image/src/haibao.jpg"></a>
			<p>
			片名：极限刺侠<br>演员：金城武 铃木杏<br>人气：1339<br>简介：太龙（金城武饰）是一个“Returner”，责任是替聘用者潜入黑市的深处，盗取大笔大笔的无迹可寻的巨款，以极高效率将款项安全交到聘用者手上。
			</p>
			<a href="#"><img src="image/main1_04.gif" width="14" height="14" align="absmiddle" border="0" class="play">播放</a></td>
			<td width="50%"><a href="info.htm"><img src="image/src/haibao.jpg"></a>
			<p>
			片名：极限刺侠<br>演员：金城武 铃木杏<br>人气：1339<br>简介：太龙（金城武饰）是一个“Returner”，责任是替聘用者潜入黑市的深处，盗取大笔大笔的无迹可寻的巨款，以极高效率将款项安全交到聘用者手上。
			</p>
			<a href="#"><img src="image/main1_04.gif" width="14" height="14" align="absmiddle" border="0" class="play">播放</a></td>
		</tr>
		<tr>
			<td height="1" colspan="2" background="image/index2_22.gif"></td>
		</tr>
		<tr>
			<td width="50%"><a href="info.htm"><img src="image/src/haibao.jpg"></a>
			<p>
			片名：极限刺侠<br>演员：金城武 铃木杏<br>人气：1339<br>简介：太龙（金城武饰）是一个“Returner”，责任是替聘用者潜入黑市的深处，盗取大笔大笔的无迹可寻的巨款，以极高效率将款项安全交到聘用者手上。
			</p>
			<a href="#"><img src="image/main1_04.gif" width="14" height="14" align="absmiddle" border="0" class="play">播放</a></td>
			<td width="50%"><a href="info.htm"><img src="image/src/haibao.jpg"></a>
			<p>
			片名：极限刺侠<br>演员：金城武 铃木杏<br>人气：1339<br>简介：太龙（金城武饰）是一个“Returner”，责任是替聘用者潜入黑市的深处，盗取大笔大笔的无迹可寻的巨款，以极高效率将款项安全交到聘用者手上。
			</p>
			<a href="#"><img src="image/main1_04.gif" width="14" height="14" align="absmiddle" border="0" class="play">播放</a></td>
		</tr>
		</table>
		</td>
		
	</tr>
	</table>
	<table id="type_navi" width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td align="center">共找到<span style="color:#ff0000">248</span>部电影 每页显示<span style="color:#ff0000">8</span>部 共<span style="color:#ff0000">31</span>页 当前第<span style="color:#ff0000">1</span>页 <a href="#">第一页</a> <a href="#">上一页</a> <a href="#">下一页</a> <a href="#">最后页</a> 跳转到第<select name="newpage">
		<option value="1">1</option>
		<option value="2">2</option>
		<option value="3">3</option>
		<option value="4">4</option>
		<option value="5">5</option>
		<option value="6">6</option>
		</select>页<br>
		</td>
	</tr>
	</table>
	</td>
	<td bgcolor="#ffffff"></td>
</tr>
<tr>
	<td height="8" background="image/index2_10.gif"></td>
	<td bgcolor="#ffffff"></td>
	<td background="image/index2_11.gif"></td>
</tr>
</table>
</div>