application: zerofault
version: 2
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /loadcsv
  script: loadcsv.py
  login: admin

- url: /dump/.*
  script: dump.py

- url: /.*
  script: main.py