truncate erp_node;

INSERT INTO erp_node VALUES("1", "0", "Supplier", "Supplier Management", "0");
INSERT INTO erp_node VALUES("2", "1", "index", "List", "0");
INSERT INTO erp_node VALUES("3", "1", "form", "Add/Edit Form", "0");
INSERT INTO erp_node VALUES("4", "1", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("5", "1", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("6", "0", "Dept", "Department Management", "0");
INSERT INTO erp_node VALUES("7", "6", "index", "List", "0");
INSERT INTO erp_node VALUES("8", "30", "index", "Query", "0");
INSERT INTO erp_node VALUES("9", "6", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("10", "6", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("11", "0", "Staff", "Staff Management", "0");
INSERT INTO erp_node VALUES("12", "11", "index", "List", "0");
INSERT INTO erp_node VALUES("13", "11", "form", "Add/Edit Form", "0");
INSERT INTO erp_node VALUES("14", "11", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("15", "11", "update", "Disable/Enable Staff", "0");
INSERT INTO erp_node VALUES("16", "0", "Category", "Category Management", "0");
INSERT INTO erp_node VALUES("17", "16", "index", "List", "0");
INSERT INTO erp_node VALUES("18", "16", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("19", "16", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("20", "0", "Product", "Component Management", "0");
INSERT INTO erp_node VALUES("21", "20", "index", "List", "0");
INSERT INTO erp_node VALUES("22", "20", "form", "Add/Edit Form", "0");
INSERT INTO erp_node VALUES("23", "20", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("24", "20", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("25", "0", "Board", "Board Management", "0");
INSERT INTO erp_node VALUES("26", "25", "index", "List", "0");
INSERT INTO erp_node VALUES("27", "25", "form", "Add/Edit Form", "0");
INSERT INTO erp_node VALUES("28", "25", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("29", "25", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("30", "0", "Inventory", "Inventory Query", "0");
INSERT INTO erp_node VALUES("31", "0", "Setting", "Options Setting", "0");
INSERT INTO erp_node VALUES("32", "0", "ProductIn", "Inventory Input Management", "0");
INSERT INTO erp_node VALUES("33", "31", "index", "List", "0");
INSERT INTO erp_node VALUES("34", "31", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("35", "31", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("36", "32", "index", "Product Entering List", "0");
INSERT INTO erp_node VALUES("38", "32", "confirm", "Confirm the Entering/Return", "0");
INSERT INTO erp_node VALUES("39", "32", "form", "Add/Edit Form", "0");
INSERT INTO erp_node VALUES("40", "32", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("41", "32", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("42", "0", "Role", "Role Management", "0");
INSERT INTO erp_node VALUES("43", "42", "index", "List", "0");
INSERT INTO erp_node VALUES("44", "0", "ProductOut", "Product Output Management", "0");
INSERT INTO erp_node VALUES("46", "44", "transfer", "Assets Transfer List", "0");
INSERT INTO erp_node VALUES("47", "44", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("48", "44", "release", "Assets Release List", "0");
INSERT INTO erp_node VALUES("49", "44", "form", "Add/Edit form", "0");
INSERT INTO erp_node VALUES("50", "44", "select", "Selection Popup", "0");
INSERT INTO erp_node VALUES("51", "44", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("52", "0", "Location", "Location Setting", "0");
INSERT INTO erp_node VALUES("53", "0", "Node", "Node Setting", "0");
INSERT INTO erp_node VALUES("54", "52", "index", "List", "0");
INSERT INTO erp_node VALUES("55", "52", "submit", "Submit adding/changing", "0");
INSERT INTO erp_node VALUES("56", "52", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("57", "53", "index", "List", "0");
INSERT INTO erp_node VALUES("58", "53", "update", "Update", "0");
INSERT INTO erp_node VALUES("59", "20", "select", "Selection popup", "0");
INSERT INTO erp_node VALUES("62", "32", "select", "Selection popup", "0");
INSERT INTO erp_node VALUES("63", "44", "applyFloating", "Floating-Assets Applying", "0");
INSERT INTO erp_node VALUES("64", "44", "scrap", "Assets Scrap List", "0");
INSERT INTO erp_node VALUES("66", "44", "confirm", "Confirm Request", "0");
INSERT INTO erp_node VALUES("67", "42", "add", "Add role", "0");
INSERT INTO erp_node VALUES("69", "42", "edit", "Edit role", "0");
INSERT INTO erp_node VALUES("70", "42", "update", "Enable/Disable role", "0");
INSERT INTO erp_node VALUES("71", "42", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("72", "11", "profile", "Edit personal profile", "0");
INSERT INTO erp_node VALUES("73", "32", "reject", "Reject Product to Supplier", "0");
INSERT INTO erp_node VALUES("74", "44", "applyFixed", "Fixed-Assets Applying", "0");
INSERT INTO erp_node VALUES("75", "44", "returns", "Assets Returning List", "0");
INSERT INTO erp_node VALUES("76", "11", "delete", "Delete", "0");
INSERT INTO erp_node VALUES("77", "32", "fixed", "Fixed-Assets Entering", "0");
INSERT INTO erp_node VALUES("78", "32", "floating", "Floating-Assets Entering", "0");
