			<table class="icon_table" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border:2px solid #141414;">
			<tr>
				<td width="226" height="140">&nbsp;</td>
				<td width="226">&nbsp;</td>
				<td width="226">&nbsp;</td>
			</tr>
			<tr>
				<td height="160"><a href="culture.php"><img src="images/1-1.gif" onmouseover="this.src='images/1-1b.gif';" onmouseout="this.src='images/1-1.gif';"/></a></td>
				<td><a href="stylist.php"><img src="images/1-2.gif" onmouseover="this.src='images/1-2b.gif';" onmouseout="this.src='images/1-2.gif';"/></a></td>
				<td><img src="images/1-3.gif" /></td>
			</tr>
			<tr>
				<td height="160"><img src="images/2-1.gif" /></td>
				<td><img src="images/2-2.gif" /></td>
				<td><a href="contact.php"><img src="images/2-3.gif" onmouseover="this.src='images/2-3b.gif';" onmouseout="this.src='images/2-3.gif';"/></a></td>
			</tr>
			<tr>
				<td height="160">&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td height="136">&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			</table>