			<table width="686" class="icon_table" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border:2px solid #141414;">
			<tr>
				<td width="226" height="140" valign="bottom" class="stylist_header">
					<b>设　计　师</b>Pierre-Marie Gallois
				</td>
				<td width="226">&nbsp;</td>
				<td width="226">&nbsp;</td>
			</tr>
			<tr>
				<td height="160"><img src="images/stylist-1.gif" /></td>
				<td rowspan="4" valign="top">
					<div class="stylist_intro">
						<h2><a href="?stylist"><img src="images/icon4.gif" align="absmiddle"/></a>Pierre-Marie Gallois</h2>
						<h3>职位：全球总裁</h3>
						<dl>
							<dt>个人简介：</dt>
							<dd>毕业于法国凡尔赛高等建筑工程师学院(ENSA Versailles)</dd>
							<dt>代 表 作：</dt>
							<dd>普罗旺斯.紫餐厅</dd>
							<dt>作品风格：</dt>
							<dd>深受印象派影响，崇尚极简风格,擅长用简洁的线条中叙述人与自然的亲密关系。</dd>
						</dl>
					</div>
				</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td height="160"><img src="images/stylist-2.gif" /></td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td height="160"><img src="images/stylist-3.gif" /></td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td height="136"><img src="images/stylist-4.gif" /></td>
				<td>&nbsp;</td>
			</tr>
			</table>
			<img class="stylist_photo" src="images/photo_Pierre.jpg" />