<?php
/**
 * Flash.cls.php
 * @author  zhangfang@bokee.com
 * @version  1.0
 * @abstract  flash头条类
 * Generated by BaseClassGen
 * @copyright bokee dot com
 */

include_once('sql/DAO.cls.php');
include_once('lang/Assert.cls.php');
require_once('mod/Subject.cls.php');
require_once('com/FTP.cls.php');

class Flash
{
	//成员变量
	/**
	* @access private
	*/
	var $_id;
	/**
	* @access private
	*/
	//成员变量
	/**
	* @access private
	*/
	var $_upload_path;
	/**
	* @access private
	*/	//成员变量
	/**
	* @access private
	*/
	var $_flash_name;
	/**
	* @access private
	*/	//成员变量
	/**
	* @access private
	*/
	var $_xml_name;
	/**
	* @access private
	*/	//成员变量
	/**
	* @access private
	*/
	var $_css_name;
	/**
	* @access private
	*/
	var $_pic_dir;	
	/**
	* @access private
	*/
	var $_name;	
	//成员函数
	/**
	* @access public
	*/
	function GetId()
	{
		return $this->_id;
	}
	/**
	* @access public
	*/
	function SetId($value)
	{
		$this->_id = $value;
	}
	//成员函数
	/**
	* @access public
	*/
	function GetName()
	{
		return $this->_name;
	}
	/**
	* @access public
	*/
	function SetName($value)
	{
		$this->_name = $value;
	}
	//成员函数
	/**
	* @access public
	*/
	function GetUploadPath()
	{
		return $this->_upload_path;
	}
	/**
	* @access public
	*/
	function SetUploadPath($value)
	{
		$this->_upload_path = $value;
	}
	//成员函数
	/**
	* @access public
	*/
	function GetFlashName()
	{
		return $this->_flash_name;
	}
	/**
	* @access public
	*/
	function SetFlashName($value)
	{
		$this->_flash_name = $value;
	}
	//成员函数
	/**
	* @access public
	*/
	function GetXmlName()
	{
		return $this->_xml_name;
	}
	/**
	* @access public
	*/
	function SetXmlName($value)
	{
		$this->_xml_name = $value;
	}
	//成员函数
	/**
	* @access public
	*/
	function GetCssName()
	{
		return $this->_css_name;
	}
	/**
	* @access public
	*/
	function SetCssName($value)
	{
		$this->_css_name = $value;
	}
	//成员函数
	/**
	* @access public
	*/
	function GetPicDir()
	{
		return $this->_pic_dir;
	}
	/**
	* @access public
	*/
	function SetPicDir($value)
	{
		$this->_pic_dir = $value;
		//$pic_path = $local_path.$this->_pic_dir;            			
		if(!is_dir($this->_pic_dir))
		{
				@mkdir($this->_pic_dir, 0700);
		}  		
	}
	/**
	* @access public
	*/
	function Flash($channel_db, $row = null)
	{ 
		//echo $channel_db;
		if(empty($row))
		{
			$this->SetName("");
			$this->SetUploadPath("");
			$this->SetFlashName("");
			$this->SetXmlName("");
			$this->SetCssName("");
			$this->SetPicDir("");
		}
		else 
		{
			$this->_row = $row;
			$this->_id = $row["id"];
			$this->_name = SetName($this->_row['name']);
			$this->SetUploadPath($this->_row['upload_path']);
			$this->SetFlashName($this->_row['flash_name']);
		    $this->SetXmlName($this->_row['xml_name']);
			$this->SetCssName($this->_row['css_name']);
			$this->SetPicDir($this->_row['pic_dir']);
		}
		$this->_db = $channel_db;
		$this->_dao = DAO::CreateInstance();
        $this->_dao->SetCurrentSchema($this->_db);
	}

	function GetLocalPath($subject_id)
	{
		$subject = new Subject($this->_db);
		$subject->GetByID($subject_id);
		$level = $subject->GetSort();
		for($i=0;$i<$level;$i++)
		{
			$subjects[$i] = $subject->GetDirName();
			$subject->GetByID($subject->GetParentId());
		}
		$local_path = PATH_HTML_ROOT . "/" . $this->_db;
		if(!is_dir($local_path))
		{
			mkdir($local_path, 0700);
		}
		for($i=$level-1;$i>=0;$i--)
		{
			$local_path .= "/" . $subjects[$i];
			//$local_path .= "/" . $subjects[$i];
			if(!is_dir($local_path))
			{
				mkdir($local_path, 0700);
			}
		}
		$local_path .= "/" . $this->_file_name;

		//log::Append($local_path);
		return $local_path;		
	}	

//	function Query($sql = "")
//	{
//		$dao = DAO::CreateInstance();
//		$dao->assoc = true;
//		$dao->SetCurrentSchema($this->_db);
//		//$dao->SetCurrentSchema("cms_life");
//
//		$result = $dao->GetPlan($sql);
//
//		$dao->Disconnect();
//
//		return $result;
//	}	
	/**
	* @access public
	* @return int
	*/
	function Insert()
	{
		$insert_clause = "insert into flash set 
		id='NULL',
		name = '$this->_name',
		upload_path = '$this->_upload_path',
		flash_name = '$this->_flash_name',
		xml_name = '$this->_xml_name',
		css_name = '$this->_css_name',
		pic_dir = '$this->_pic_dir'
		";
		if($this->_dao->Insert($insert_clause))
		{
			return $this->_dao->LastID();
		}
		else 
		{
			return -1;
		}
	}
//
//	/**
//	* @access public
//	* @param int $id
//	* @return bool
//	*/
//	function DeleteByID($id)
//	{
//		$this->_id = intval($id);
//		echo $delete_clause = "delete from header where id= $this->_id";
//		return $this->_dao->Query($delete_clause);
//	}
//	/**
//	* @access public
//	* @param int $id
//	* @return bool
//	*/
//	function DeletesubByID($id)
//	{
//		$this->_id = intval($id);
//		$sql="select * from header";
//	    $rows=$this->_dao->GetPlan($sql);
//	   
//	    for($i=0;$i<count($rows);$i++)
//	    {
//	    	if(!empty($rows[$i]['child_id']))
//	    	{
//	    		$rows[$i]['child_id'];
//	    		$pieces = explode("|", $rows[$i]['child_id']);
//	                 	
//                for($j=0;$j<count($pieces);$j++)
//		        {   
//			         if($pieces[$j] == $id)
//			            $pieces[$j]="";
//			          else 
//			            $pieces[$j]=$pieces[$j]."|";
//			         $new_child .= $pieces[$j];
//		        }
//		        $len=strlen($new_child)-1;
//		        $new_childs=substr($new_child,0,$len);
//		        $update_clause = "update header set child_id = '$new_childs' where id=".$rows[$i]['id']."";
//		        $this->_dao->Query($update_clause);
//		        $new_child=""; 		        
//	    	}
//	  }
//	}
//	function GetByID($id)
//	{
//		$this->_id = intval($id);
//		if($this->_id == 0)
//			return false;
//		$get_clause = "select * from header where id=$this->_id";
//		$this->_row=$this->_dao->GetRow($get_clause);
//		//print_r($this->_row);
//		if(!$this->_row)
//		{
//			Log::Append("文件:" . __FILE__ . " 第 " . __LINE__ . " 行附近 根据ID获取栏目 出错。");
//			return false;
//		}
//		$this->SetSubjectId($this->_row['subject_id']);
//		$this->SetName($this->_row['name']);		
//		$this->SetContent($this->_row['content']);
//		$this->SetImageUrl($this->_row['image_url']);
//	    $this->SetImageLink($this->_row['image_link']);
//	    $this->SetChildId($this->_row['child_id']);
//		$this->SetParentId($this->_row['parent_id']);
//		$this->SetChoice($this->_row['choice']);
//	    $this->SetUpdateDate($this->_row['update_date']);
//		return true;
//	}
//	/**
//	* @access public
//	* @return bool
//	*/
//	function Update()
//	{
//		echo $update_clause = "update header set 
//		subject_id = '$this->_subject_id',
//		name = '$this->_name',
//		content = '$this->_content',
//		image_url = '$this->_image_url',
//		image_link = '$this->_image_link',
//		child_id = '$this->_child_id',
//		parent_id = '$this->_parent_id',
//		choice = '$this->_choice',
//		update_date = '$this->_update_date'
//		where id = $this->_id
//		";
//		return $this->_dao->Update($update_clause);
//	}
//	/**
//	* @access public
//	* @return bool
//	*/
//	function UpdateChoice()
//	{
//		echo $update_clause = "update header set 
//		choice = 'N',
//		update_date = '$this->_update_date'
//		where (subject_id = $this->_subject_id) and (id<>$this->_id)
//		";
//		return $this->_dao->Update($update_clause);
//	}	
//	/**
//	* @access public
//	* @abstract 发布
//	*/
//	function Publish()
//	{
//		$this->_path = PATH_HTML_ROOT . "/" . $this->_db . "/header/" . $this->_subject_id . ".html";
//
//		if(!file_exists(PATH_HTML_ROOT . "/" . $this->_db . "/header/"))
//			mkdir(PATH_HTML_ROOT . "/" . $this->_db . "/header/");
//		if($fp = fopen($this->_path, 'w'))
//		{
//			fwrite($fp, $this->_content);
//		}
//		else
//		{
//			die("error");
//		}
//		fclose($fp);
//		$remote_path = "/html/" . $this->_db . "/header/". $this->_subject_id . ".html";
//		//计算发布路径
//		$ftp = new FTP();
//		$ftp->Put($this->_path, $remote_path);
//	}
//	/**
//	* @access public
//	* @param int $id
//	* @return bool
//	*/
//	function ModifysubByID($id)
//	{
//		echo $this->_id = intval($id);
//		$sql="select * from header where child_id<>'0'";
//	    $rows=$this->_dao->GetPlan($sql);
//	   //print_r($rows);
//	    for($i=0;$i<count($rows);$i++)
//	    {
//	    		$pieces[$i] = explode("|", $rows[$i]['child_id']);	   	              	
//                for($j=0;$j<count($pieces[$i]);$j++)
//		        {   
//		        	if($pieces[$i][$j]==$id)
//		        	{		    		
//		        		  for($k=0;$k<count($pieces[$i]);$k++)
//		                  { 
//		                  	  
//		                  	  echo $sql="select * from header where subject_id=".$pieces[$i][$k]." and choice='Y'";
//	                          $row=$this->_dao->GetRow($sql);	                          
//	                          echo $content .= $row['content'];  	                         	    	
//		                  }
//		                 echo $sql="update header set content='$content' where id=".$rows[$i]['id']."";    			          
//    	                 $this->_dao->Update($sql);
//    	                 if($rows[$i]['choice']=='Y')
//    	                 {
//    	        	          $this->_subject_id = $rows[$i]['subject_id'];
//    	        	          $this->_content=$content;
//    	        	          $this->Publish();
//    	                 }
//		        	}
//		        	$content="";
//		        }
//	    }    		 
//	}
//	/**
//	* @access public
//	* @param int $id
//	* @return bool
//	*/
//	function ModifySsubByID($id)
//	{
//		$this->_id = intval($id);
//		$sql="select * from header where child_id<>'0'";
//	    $rows=$this->_dao->GetPlan($sql);
//	  // print_r($rows);
//	    for($i=0;$i<count($rows);$i++)
//	    {
//	    		$pieces[$i] = explode("|", $rows[$i]['child_id']);	   	              	
//                for($j=0;$j<count($pieces[$i]);$j++)
//		        {   
//		        	if($pieces[$i][$j]==$id)
//		        	{		   		
//		        		  for($k=0;$k<count($pieces[$i]);$k++)
//		                  { 		                  	  
//		                  	  $sql="select * from header where subject_id=".$pieces[$i][$k]." and choice='Y'";
//	                          $row=$this->_dao->GetRow($sql);
//	                          if($id!= $pieces[$i][$k])	                          
//	                              $content .= $row['content'];  	                         	    	
//		                  }
//		                 echo $sql="update header set content='$content' where id=".$rows[$i]['id']."";    			          
//    	                 $this->_dao->Update($sql);
//    	                 if($rows[$i]['choice']=='Y')
//    	                 {
//    	        	          $this->_subject_id = $rows[$i]['subject_id'];
//    	        	          $this->_content=$content;
//    	        	          $this->Publish();
//    	                 }
//		        	}
//		        	$content="";
//		        }
//	    }    	
//	 
//	}
}
?>