<?php
/**
 * Gallery.cls.php
 * Generated by BaseClassGen
 * @copyright bokee dot com
 * created at August 12, 2005, 13:22:37
 */

include_once('sql/DAO.cls.php');
include_once('lang/Assert.cls.php');
require_once('com/Log.cls.php');

class Gallery
{
	//Properties
	var $_row;
	/**
	* @access private
	*/
	var $_id;
	/**
	* @access private
	*/
	var $_name;
	/**
	* @access private
	*/
	var $_article_id;
	/**
	* @access private
	*/
	var $_path;
	/**
	* @access private
	*/
	var $_create_time;
	/**
	* @access private
	*/
	var $_user_id;
	/**
	* @access private
	*/
	var $_dao;
	/**
	* @access private
	*/
	var $_p_content;
	/**
	* @access private
	*/
    var $_images_textId;
    
    var $_subject_id;
	var $_url;
	var $_category;
	var $_description;
	var $_group_id;
	
	//Methods
	/**
	* @access public
	*/
	function GetId()
	{
		return $this->_id;
	}
	/**
	* @access public
	*/
	function SetId($value)
	{
		$this->_id = $value;
	}
	/**
	* @access public
	*/
	function SetArticleId($value)
	{
		$this->_article_id = $value;
	}
	/**
	* @access public
	*/
	function GetArticleId()
	{
		return $this->_aritlce_id;
	}
	/**
	* @access public
	*/
	function GetName()
	{
		return $this->_name;
	}
	/**
	* @access public
	*/
	function SetName($value)
	{
		$this->_name = $value;
	}
	/**
	* @access public
	*/
	function Setpcontent($value)
	{
		$this->_p_content = $value;
	}
	/**
	* @access public
	*/
	function GetPath()
	{
		return $this->_path;
	}
	/**
	* @access public
	*/
	function SetPath($value)
	{
		$this->_path = $value;
	}
	/**
	* @access public
	*/
	function GetCreateTime()
	{
		return $this->_create_time;
	}
	/**
	* @access public
	*/
	function SetCreateTime($value)
	{
		$this->_create_time = $value;
	}
	/**
	* @access public
	*/
	function GetUserId()
	{
		return $this->_user_id;
	}
	/**
	* @access public
	*/
	function Setimages_textId($value)
	{
		$this->_images_textId = $value;
	}
	/**
	* @access public
	*/
	function SetUserId($value)
	{
		$this->_user_id = $value;
	}
	function GetSubjectId()
	{
		return $this->_subject_id;
	}
	function SetSubjectId($value)
	{
		$this->_subject_id = $value;
	}
	function GetUrl()
	{
		return $this->_url;
	}
	function SetUrl($value)
	{
		$this->_url = $value;
	}
	function SetCategory($value)
	{
		$this->_category = $value;
	}
	function GetCategory()
	{
		return $this->_category;
	}
	function SetDescription($value)
	{
		$this->_description = $value;
	}
	function GetDescription()
	{
		return $this->_description;
	}
	function SetGroupID($value)
	{
		$this->_group_id = $value;
	}
	function GetGroupID()
	{
		return $this->_group_id;
	}
	
	/**
	* @access public
	* @param string $channel_db
	* @param array $row;
	*/
	function Gallery($channel_db, $row = null)
	{
		if(empty($row))
		{
			$this->SetName("");
			$this->SetPath("");
			$this->SetCreateTime("");
			$this->SetUserId(0);
			$this->SetSubjectId(0);
			$this->SetArticleId(0);
			$this->SetUrl("");
			$this->SetCategory(0);
			$this->SetDescription("");
			$this->SetGroupID(0);
		}
		else 
		{
			$this->_row = $row;
			$this->SetName($this->_row['name']);
			$this->SetPath($this->_row['path']);
			$this->SetCreateTime($this->_row['create_time']);
			$this->SetUserId($this->_row['user_id']);
			$this->SetSubjectId($this->_row['subject_id']);
			$this->SetArticleId($this->_row['article_id']);
			$this->SetUrl($this->_row['url']);
			$this->SetCategory($this->_row['category']);
			$this->SetDescription($this->_row['description']);
			$this->SetGroupID($this->_row['group_id']);
		}
		$this->_db = $channel_db;
		$this->_dao = DAO::CreateInstance();
        $this->_dao->SetCurrentSchema($this->_db);
	}
	/**
	* @access public 
	* @return bool
	*/
	function Get()
	{
		if($this->_id>0)
		{
			return $this->GetByID($this->_id);
		}
		else 
		{
			return false;
		}
	}
	/**
	* @access public
	* @param int $id
	* @return bool
	*/
	function GetByID($id)
	{
		$this->_id = intval($id);
		$get_clause = "select * from gallery where id=$this->_id";
		$this->_row=$this->_dao->GetRow($get_clause);
		if(!$this->_row)
			return false;
		$this->SetName($this->_row['name']);
		$this->SetPath($this->_row['path']);
		$this->SetCreateTime($this->_row['create_time']);
		$this->SetUserId($this->_row['user_id']);
		$this->SetSubjectId($this->_row['subject_id']);
		$this->SetArticleId($this->_row['article_id']);
		$this->SetUrl($this->_row['url']);
		$this->SetCategory($this->_row['category']);
		$this->SetDescription($this->_row['description']);
		$this->SetGroupID($this->_row['group_id']);
		return true;
	}
	/**
	* @access public
	* @return bool
	*/
	function Update()
	{
		$update_clause = "update gallery set 
		name = '$this->_name',
		path = '$this->_path',
		user_id = $this->_user_id,
		subject_id = $this->_subject_id,
		article_id = $this->_article_id,
		url = '$this->_url',
		category = $this->_category,
		description = '$this->_description',
		group_id = $this->_group_id
		where id=$this->_id
		";
		return $this->_dao->Update($update_clause);
	}
	function UpdateUrl()
	{
		$update_clause = "update gallery set 
		url = '$this->_url'
		where id=$this->_id
		";
		return $this->_dao->Update($update_clause);
	}
	/**
	* @access public
	* @return bool
	*/
	function Delete()
	{
		if($this->_id>0)
		{
			return $this->DeleteByID($this->_id);
		}
		else 
		{
			return false;
		}
	}
	/**
	* @access public
	* @param int $id
	* @return bool
	*/
	function DeleteByID($id)
	{
		$this->_id = intval($id);
		$delete_clause = "delete from gallery where id= $this->_id";
		return $this->_dao->Query($delete_clause);
	}
	/**
	* @access public
	* @return int
	*/
	function Insert()
	{		
		$insert_clause = "insert into gallery set 
		article_id=$this->_article_id,
		name = '$this->_name',
		path = '$this->_path',
		create_time = '" . date('Y-m-d H:i:s') . "',
		user_id =$this->_user_id,
		subject_id = $this->_subject_id,
		url = '$this->_url',
		category = $this->_category,
		description = '$this->_description',
		group_id = $this->_group_id
		";
		//Log::Append("文件:" . __FILE__ . " 第 " . __LINE__ . " 行附近sql:" . $insert_clause);
		if($this->_dao->Insert($insert_clause))
		{ 
			return $this->_dao->LastID();
		}
		else 
		{
			return -1;
		}
	}
}
?>