<?php
/**
 * Header.cls.php
 * @author  zhangfang@bokee.com
 * @version  1.0
 * @abstract  头条类
 * Generated by BaseClassGen
 * @copyright bokee dot com
 * created at August 12, 2005, 13:22:37
 */

include_once('sql/DAO.cls.php');
include_once('lang/Assert.cls.php');
require_once('mod/Subject.cls.php');
require_once('com/FTP.cls.php');

class Header
{
	//成员变量
	/**
	* @access private
	*/
	var $_id;
	/**
	* @access private
	*/
	var $_subject_id;
	/**
	* @access private
	*/
	var $_name;
	/**
	* @access private
	*/
	var $_content;
	/**
	* @access private
	*/
	var $_image_url;
	/**
	* @access private
	*/
	var $_child_id;
	/**
	* @access private
	*/
	var $_dao;
	/**
	* @access private
	*/
	var $_row;
	/**
	* @access private
	*/
	var $_parent_id;
	/**
	* @access private
	*/
	var $_update_date;
	/**
	* @access private
	*/
	var $_choice;

	//成员函数
	/**
	* @access public
	*/
	function GetId()
	{
		return $this->_id;
	}
	/**
	* @access public
	*/
	function SetId($value)
	{
		$this->_id = $value;
	}
	/**
	* @access public
	*/
	function GetSubjectId()
	{
		return $this->_subject_id;
	}
	/**
	* @access public
	*/
	function SetSubjectId($value)
	{
		$this->_subject_id = $value;
	}
	/**
	* @access public
	*/
	function GetContent()
	{
		return $this->_content;
	}
	/**
	* @access public
	*/
	function SetContent($value)
	{
		$this->_content = $value;
	}
	/**
	* @access public
	*/
	function SetImageUrl($value)
	{
		$this->_image_url = $value;
	}
	/**
	* @access public
	*/
	function GetImageUrl()
	{
		return $this->_image_url;
	}
	/**
	* @access public
	*/
	function SetImageLink($value)
	{
		$this->_image_link = $value;
	}
	/**
	* @access public
	*/
	function GetImageLink()
	{
		return $this->_image_link;
	}
	/**
	* @access public
	*/
	function SetChildId($value)
	{
		$this->_child_id = $value;
	}
	/**
	* @access public
	*/
	function GetChildId()
	{
		return $this->_child_id;
	}
	/**
	* @access public
	*/
	function SetParentId($value)
	{
		$this->_parent_id = $value;
	}
	/**
	* @access public
	*/
	function GetParentId()
	{
		return $this->_parent_id;
	}
	/**
	* @access public
	* @param int $value
	* @return bool
	*/
	function SetUpdateDate($value)
	{
		$this->_update_date = $value;
		return true;
	}
	/**
	* @access public
	*/
	function GetUpdateDate()
	{
		return $this->_update_date;
	}
	/**
	* @access public
	* @param int $value
	* @return bool
	*/
	function SetName($value)
	{
		$this->_name = $value;
		return true;
	}
	/**
	* @access public
	*/
	function GetName()
	{
		return $this->_name;
	}
	/**
	* @access public
	* @param int $value
	* @return bool
	*/
	function SetChoice($value)
	{
		$this->_choice = $value;
		return true;
	}
	/**
	* @access public
	*/
	function GetChoice()
	{
		return $this->_choice;
	}
	/**
	* @access public
	*/
	function Header($channel_db, $row = null)
	{
		if(empty($row))
		{
			$this->SetSubjectId(0);
			$this->SetContent(0);
			$this->SetImageUrl("");
			$this->SetChildId(0);
			//$this->SetParentId(0);
			$this->SetUpdateDate("");
		}
		else 
		{
			$this->_row = $row;
			$this->_id = $row["id"];
			$this->SetSubjectId($this->_row['subject_id']);
			$this->SetContent($this->_row['content']);
			$this->SetImageUrl($this->_row['imageurl']);
			$this->SeChildId($this->_row['child_id']);
			$this->SetParentId($this->_row['parent_id']);
			$this->SetChoice($this->_row['choice']);
			$this->SetUpdateDate($this->_row['update_date']);
		}
		$this->_db = $channel_db;
		$this->_dao = DAO::CreateInstance();
        $this->_dao->SetCurrentSchema($this->_db);
	}

	function Query($sql = "")
	{
		$dao = DAO::CreateInstance();
		$dao->assoc = true;
		$dao->SetCurrentSchema($this->_db);
		//$dao->SetCurrentSchema("cms_life");

		$result = $dao->GetPlan($sql);

		$dao->Disconnect();

		return $result;
	}	
	/**
	* @access public
	* @return int
	*/
	function Insert()
	{
		echo $insert_clause = "insert into header set 
		id='NULL',
		name = '$this->_name',
		subject_id = '$this->_subject_id',
		content = '$this->_content',
		image_url = '$this->_image_url',
		child_id = '$this->_child_id',
        parent_id = '$this->_parent_id',
        choice = '$this->_choice',
        update_date = '$this->_update_date'
		";
		if($this->_dao->Insert($insert_clause))
		{
			return $this->_dao->LastID();
		}
		else 
		{
			return -1;
		}
	}

	/**
	* @access public
	* @param int $id
	* @return bool
	*/
	function DeleteByID($id)
	{
		$this->_id = intval($id);
		echo $delete_clause = "delete from header where id= $this->_id";
		return $this->_dao->Query($delete_clause);
	}
	/**
	* @access public
	* @param int $id
	* @return bool
	*/
	function DeletesubByID($id)
	{
		$this->_id = intval($id);
		$sql="select * from header";
	    $rows=$this->_dao->GetPlan($sql);
	   
	    for($i=0;$i<count($rows);$i++)
	    {
	    	if(!empty($rows[$i]['child_id']))
	    	{
	    		$rows[$i]['child_id'];
	    		$pieces = explode("|", $rows[$i]['child_id']);
	                 	
                for($j=0;$j<count($pieces);$j++)
		        {   
			         if($pieces[$j] == $id)
			            $pieces[$j]="";
			          else 
			            $pieces[$j]=$pieces[$j]."|";
			         $new_child .= $pieces[$j];
		        }
		        $len=strlen($new_child)-1;
		        $new_childs=substr($new_child,0,$len);
		        $update_clause = "update header set child_id = '$new_childs' where id=".$rows[$i]['id']."";
		        $this->_dao->Query($update_clause);
		        $new_child=""; 		        
	    	}
	  }
	}
	function GetByID($id)
	{
		$this->_id = intval($id);
		if($this->_id == 0)
			return false;
		$get_clause = "select * from header where id=$this->_id";
		$this->_row=$this->_dao->GetRow($get_clause);
		//print_r($this->_row);
		if(!$this->_row)
		{
			Log::Append("文件:" . __FILE__ . " 第 " . __LINE__ . " 行附近 根据ID获取栏目 出错。");
			return false;
		}
		$this->SetSubjectId($this->_row['subject_id']);
		$this->SetName($this->_row['name']);		
		$this->SetContent($this->_row['content']);
		$this->SetImageUrl($this->_row['image_url']);
	    $this->SetImageLink($this->_row['image_link']);
	    $this->SetChildId($this->_row['child_id']);
		$this->SetParentId($this->_row['parent_id']);
		$this->SetChoice($this->_row['choice']);
	    $this->SetUpdateDate($this->_row['update_date']);
		return true;
	}
	/**
	* @access public
	* @return bool
	*/
	function Update()
	{
		echo $update_clause = "update header set 
		subject_id = '$this->_subject_id',
		name = '$this->_name',
		content = '$this->_content',
		image_url = '$this->_image_url',
		image_link = '$this->_image_link',
		child_id = '$this->_child_id',
		parent_id = '$this->_parent_id',
		choice = '$this->_choice',
		update_date = '$this->_update_date'
		where id = $this->_id
		";
		return $this->_dao->Update($update_clause);
	}
	/**
	* @access public
	* @return bool
	*/
	function UpdateChoice()
	{
		echo $update_clause = "update header set 
		choice = 'N',
		update_date = '$this->_update_date'
		where (subject_id = $this->_subject_id) and (id<>$this->_id)
		";
		return $this->_dao->Update($update_clause);
	}	
	/**
	* @access public
	* @abstract 发布
	*/
	function Publish()
	{
		$this->_path = PATH_HTML_ROOT . "/" . $this->_db . "/header/" . $this->_subject_id . ".html";

		if(!file_exists(PATH_HTML_ROOT . "/" . $this->_db . "/header/"))
			mkdir(PATH_HTML_ROOT . "/" . $this->_db . "/header/");
		if($fp = fopen($this->_path, 'w'))
		{
			fwrite($fp, $this->_content);
		}
		else
		{
			die("error");
		}
		fclose($fp);
		$remote_path = "/html/" . $this->_db . "/header/". $this->_subject_id . ".html";
		//计算发布路径
		$ftp = new FTP(substr($this->_db,4));
		$ftp->Put($this->_path, $remote_path);
	}
	/**
	* @access public
	* @param int $id
	* @return bool
	*/
	function ModifysubByID($id)
	{
		echo $this->_id = intval($id);
		$sql="select * from header where child_id<>'0'";
	    $rows=$this->_dao->GetPlan($sql);
	   //print_r($rows);
	    for($i=0;$i<count($rows);$i++)
	    {
	    		$pieces[$i] = explode("|", $rows[$i]['child_id']);	   	              	
                for($j=0;$j<count($pieces[$i]);$j++)
		        {   
		        	if($pieces[$i][$j]==$id)
		        	{		    		
		        		  for($k=0;$k<count($pieces[$i]);$k++)
		                  { 
		                  	  
		                  	  echo $sql="select * from header where subject_id=".$pieces[$i][$k]." and choice='Y'";
	                          $row=$this->_dao->GetRow($sql);	                          
	                          echo $content .= $row['content'];  	                         	    	
		                  }
		                 echo $sql="update header set content='$content' where id=".$rows[$i]['id']."";    			          
    	                 $this->_dao->Update($sql);
    	                 if($rows[$i]['choice']=='Y')
    	                 {
    	        	          $this->_subject_id = $rows[$i]['subject_id'];
    	        	          $this->_content=$content;
    	        	          $this->Publish();
    	                 }
		        	}
		        	$content="";
		        }
	    }    		 
	}
	/**
	* @access public
	* @param int $id
	* @return bool
	*/
	function ModifySsubByID($id)
	{
		$this->_id = intval($id);
		$sql="select * from header where child_id<>'0'";
	    $rows=$this->_dao->GetPlan($sql);
	  // print_r($rows);
	    for($i=0;$i<count($rows);$i++)
	    {
	    		$pieces[$i] = explode("|", $rows[$i]['child_id']);	   	              	
                for($j=0;$j<count($pieces[$i]);$j++)
		        {   
		        	if($pieces[$i][$j]==$id)
		        	{		   		
		        		  for($k=0;$k<count($pieces[$i]);$k++)
		                  { 		                  	  
		                  	  $sql="select * from header where subject_id=".$pieces[$i][$k]." and choice='Y'";
	                          $row=$this->_dao->GetRow($sql);
	                          if($id!= $pieces[$i][$k])	                          
	                              $content .= $row['content'];  	                         	    	
		                  }
		                 echo $sql="update header set content='$content' where id=".$rows[$i]['id']."";    			          
    	                 $this->_dao->Update($sql);
    	                 if($rows[$i]['choice']=='Y')
    	                 {
    	        	          $this->_subject_id = $rows[$i]['subject_id'];
    	        	          $this->_content=$content;
    	        	          $this->Publish();
    	                 }
		        	}
		        	$content="";
		        }
	    }    	
	 
	}
}
?>