application: z-note
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /media
  static_dir: media

- url: /gbook/.*
  script: gbook.py

- url: /.*
  script: main.py