application: z-note
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /media
  static_dir: media

- url: /load
  script: loader.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

- url: /parse
  script: parse.py

- url: /dump/.*
  script: dump.py

- url: /rss/.*
  script: dump.py

- url: /.*
  script: main.py